### ISSUE TITLE
Double scrobble

### ISSUE THREAD

**Issue by TimerWolf** [Saiyato/volumio-lastfm-plugin#10]
For some reason i don´t know when, it could be if you start the track and then restart it from the start it makes double scrobble.

It can be in some other case as well but not when you just lets the songs play from an list then it seems to work fine and i think this has to be investigating more but it is for sure a bug.

A way to avoid this, i don´t know the last.fm API but it should be some way to fetch the last scrobbled track, and if that match the current one just ignore it in my case if "witch i never do" would pay a song on repeat 5 times i still make sure its only seems as it scrobbled once so this would be a nice work around for my problem.

But may not things the real problems for others.......

**Comment by Saiyato** [comment]
You are right, if you rewind the track, it can be scrobbled twice. However, if you set it to scrobble only at 99%; chances are slim it will happen.
