### ISSUE TITLE
Fatal error with connection issues

### ISSUE THREAD

**Issue by kionez** [Saiyato/volumio-lastfm-plugin#11]
I was listening some album when suddenly volumio stopped after a track, I restarted with play button but volumio stopped at the end of the song.. 
Looking in the log I discovered that due to connection problems (internet temporarily down) the plugin crashes the whole system if it can not connect\resolve ws.audioscrobbler.com.

I'm searching for a solution reading the source code, but in the meantime I've decided to report the problem, here's the log:

Jan 29 20:29:16 volumio volumio[3397]: |||||||||||||||||||||||| WARNING: FATAL ERROR |||||||||||||||||||||||||||||||||||||||||||||||||||||||||||||||||||
Jan 29 20:29:16 volumio volumio[3397]: { Error: getaddrinfo ENOTFOUND ws.audioscrobbler.com ws.audioscrobbler.com:80
Jan 29 20:29:16 volumio volumio[3397]: at errnoException (dns.js:50:10)
Jan 29 20:29:16 volumio volumio[3397]: at GetAddrInfoReqWrap.onlookup [as oncomplete] (dns.js:92:26)
Jan 29 20:29:16 volumio volumio[3397]: code: 'ENOTFOUND',
Jan 29 20:29:16 volumio volumio[3397]: errno: 'ENOTFOUND',
Jan 29 20:29:16 volumio volumio[3397]: syscall: 'getaddrinfo',
Jan 29 20:29:16 volumio volumio[3397]: hostname: 'ws.audioscrobbler.com',
Jan 29 20:29:16 volumio volumio[3397]: host: 'ws.audioscrobbler.com',
Jan 29 20:29:16 volumio volumio[3397]: port: 80 }
Jan 29 20:29:16 volumio volumio[3397]: |||||||||||||||||||||||||||||||||||||||||||||||||||||||||||||||||||||||||||||||||||||||||||||||||||||||||||||||||

**Comment by kionez** [comment]
Premise: I don't have experience with NodeJS :)

I can reproduce the error with a simple virtual instance of volumio, blocking access to ws.audioscrobbler.com via iptables. If I set the "Scrobble treshold" to 5% the system crashes faster.

Seems that simple-lastfm module doesn't handle errors, so I'm trying to add some error handling to /data/plugins/miscellanea/lastfm/node_modules/simple-lastfm/lib/index.js, adding a simple:

```
       }).on('error', function(e) {
               if (this.debug)
                       console.error('***** Got error: ', e);
       });
```
to every http.get request... Now volumio doesn't crash with "FATAL ERROR", but there's something with timers that cause skipping to next track if something fails.. I'm trying to call the callback with error parameter, but there's something wrong (mainly because I don't know how this feature works :) )

k.

**Comment by Saiyato** [comment]
Hi,

This is a good find, I'm not sure how to best handle this. First of all Volumio shouldn't crash, that much is sure. But when the internet's down should we just ignore the scrobble, or queue it (if that's even possible).

Then there's the "now playing" part, this it called on every new state push, so that's problematic as well.

**Comment by kionez** [comment]
Volumio goes to crash because of an unhandled exception, but there's something to fix in the plugin.

I'm trying to guess the correct response\callback needed to every functions call, so it should not fail and skip to next song... but for me is a trial&error process, because I don't know Node and its architecture.

I'm doing my best to fix this issue, but I don't know if I'll succeed :)

On my previous mpd installation I used mpdscribble [1], but is a simple mpd client that read the playing status and send it to lasftm, without any other interaction (i.e.: title correction).

1: https://www.musicpd.org/clients/mpdscribble/

**Comment by Saiyato** [comment]
Oh I agree it should be fixed in the plugin. I'm just thinking out loud on how to go about it.
I can add some catches, but I must make sure the timers won't freak out ;)

**Comment by kionez** [comment]
Ok, I add some code to handle error in request, seems working fine, but I'm not sure :)

https://gist.github.com/kionez/c069e97eb9d914c7560817ac61f32814

It is ugly and probably wrong, but maybe it helps.. 

A more clean solution should be using another module, but this task is far beyond my possibilities :)

**Comment by kionez** [comment]
Are there any news on this issue?

**Comment by Saiyato** [comment]
Should be fixed in the new version, just created a PR: https://github.com/volumio/volumio-plugins/pull/364
