### ISSUE TITLE
Does not scrobble TIDAL tracks

### ISSUE THREAD

**Issue by tomstephens89** [Saiyato/volumio-lastfm-plugin#14]
When TIDAL tracks are played via the volumio interface, they appear as 'now scrobbling' but are not recorded.

https://forum.volumio.org/lastfm-plugin-won-scrobble-tidal-tracks-t13466.html

**Comment by Saiyato** [comment]
Can you try the latest version and add the tidal service (not sure what it's called in the state) to the config? Not every service is supported, since the plugin will need to distinguish between streaming services that do not supply track length and the ones that do

Thanks

**Comment by tomstephens89** [comment]
I will install the latest as per the playback bug you have replied to as well.

When you say add to config, do you mean add the name (assuming 'tidal') to the scrobble/stream sources boxes.

**Comment by Saiyato** [comment]
Yes, in the config UI there should be a comma separated list, to which you can add Tidal. If you enable debug logging you'll log the 'state' as well, which should give you the service name. But my guess is that it will simply be 'tidal'. ;)

**Comment by tomstephens89** [comment]
Should I put 'tidal' in the 'Supported services providing track information' box or the 'Supported streaming services' box?

**Comment by Saiyato** [comment]
I think the first one, as Tidal should be providing all necessary info

**Comment by tomstephens89** [comment]
Trying a TIDAL track with 'tidal' in the first box and this is the log message. It does appear on lastfm as 'now scrobbling' but won't record to the history.

`2019-12-16T21:11:24.615Z - info: [LastFM] can not scrobble; state object: {"status":"play","position":0,"title":"How Can I Lose Your Love","artist":"The Darkness","album":"Easter is Cancelled (Deluxe)","albumart":"https://resources.tidal.com/images/39260fa9/984a/4063/9d54/8b36ec80988a/640x640.jpg","uri":"http://sp-pr-fa.audio.tidal.com/mediatracks/CAEaKRInMDVjZTk0MDM0MDQ2M2I1NmI3MmQ3NzRiMWE5MjYyNGFfNjEubXA0/0.flac?token=1576534283~NzRkZDJlZjkxOGY5YTU5OWNiYjYxYjNiYmJiYWUwMDVmOWYyNzNjZg==","trackType":"tidal","seek":464,"duration":183,"samplerate":"44.1 kHz","bitdepth":"16 bit","channels":2,"random":false,"repeat":false,"repeatSingle":false,"consume":true,"volume":100,"mute":false,"disableVolumeControl":true,"stream":false,"updatedb":false,"volatile":false}
`

**Comment by tomstephens89** [comment]
Any news on this? Thanks for fixing the other one!

**Comment by oisteink** [comment]
On my install the Tidal service has the brilliant name of "undefined" - I believe the Tidal part of Volumio is still beta - at least it has a lot of issues. EDIT: My current "Supported services providing track info" is: undefined,mpd,airplay,volspotconnect,volspotconnect2,spop

--------------------------------------------------------------------// [LastFM] new state has been pushed; 
status: play | service: undefined | duration: 245 | title: Explode | previous title: Erase / Rewind

Adding same log here that I did previously - 2 tidal songs played. Using version from yesterday - seems to me that you pushed all changes into that one.
[log-2tidal-songs.txt](https://github.com/Saiyato/volumio-lastfm-plugin/files/3990465/log-2tidal-songs.txt)

**Comment by timvanrooyen** [comment]
info: [LastFM] can not scrobble; state object: {"status":"play","title":"Leidenschaft","artist":"Jazz Dialogue & Philanthrope","album":"Quintessenz Und Ihre Nuance Instrumentals","albumart":"https://resources.tidal.com/images/4224cce9/aade/47bf/a95d/079b23dcd7a3/1280x1280.jpg","uri":"","trackType":"tidal","seek":69638,"duration":202,"samplerate":"44.1 KHz","bitdepth":"16 bit","channels":2,"random":false,"repeat":false,"repeatSingle":false,"consume":false,"volume":61,"dbVolume":null,"mute":false,"disableVolumeControl":false,"stream":false,"updatedb":false,"volatile":true,"service":"tidalconnect"}

**Comment by timvanrooyen** [comment]
Changing settings to include tidal and tidalconnect worked for 
<img width="925" alt="Screenshot 2021-12-04 at 15 02 26" src="https://user-images.githubusercontent.com/5550208/144710477-a61fd183-3a17-414b-9dc0-985779c43423.png">
me

**Comment by Saiyato** [comment]
Hi,

I just merged a lot of changes in logic upstream, Hopefully I'll be able to release a new version in the coming weeks.
But yes, adding the services will make sure Tidal is also scrobbled :wink:

I will add it by default in the new builds

**Comment by timvanrooyen** [comment]
Thanks! Looking forward to having the plugin available in Volumio 3!

Regards

Tim van Rooyen

**Comment by Saiyato** [comment]
Reworked the changes from the merge, philosophy is now blacklist what you DON'T want to scrobble :wink: It tries to scrobble for all services, unless blacklisted. Use version 1.5.3 and up
