### ISSUE TITLE
Scrobble Threshold dropdown menu disappears

### ISSUE THREAD

**Issue by nigiriemoji** [Saiyato/volumio-lastfm-plugin#16]
Hello,

I'm on Volumio 2.779 on last.fm plugin 1.3.4. When I click on the Scrobble Threshold dropdown menu it disappears completely, can't change from 75%. How do I edit this in the webGUI? Or can I do this with CLI? If so where do I go for that?

**Comment by nigiriemoji** [comment]
<img width="554" alt="image" src="https://user-images.githubusercontent.com/53108354/87190094-b5485e80-c2a6-11ea-94da-8d863f2d30e4.png">

Here's what I see

**Comment by jasonkguinn** [comment]
I am experiencing the same behavior. I attempted to change the setting in the /data/plugins/miscellanea/lastfm/config.json file but it does not seem to be acknowledging the change I made within that file (from its initial parameter of 75 to 25) - even after a restart.

**Comment by Saiyato** [comment]
Somewhere along the road the predefined drop-down items (read from file synchronously) stopped functioning. This I can confirm this, because I had to patch a few other plugins as well. Will try to make some time for this plugin, but admission in the official plugin store can take some time.

**Comment by Saiyato** [comment]
Settings are now hard-coded, as the referenced synchronous load from a config file doesn't work anymore as of a certain version. Please use version 1.5.2 and up
