### ISSUE TITLE
Scrobbles are not recorded when airplaying to Volumio

### ISSUE THREAD

**Issue by christophertappin** [Saiyato/volumio-lastfm-plugin#17]
Hi,

When I airplay to Volumio, the currently playing track appears in last.fm as “Now playing” but the track is never recorded, it just disappears and moves onto the next track.

I notice there’s an open issue where Tidal tracks display the same behaviour so I’m not sure if this issue might be related.

Is there any config I need to do?

Thanks

**Comment by matthewrt** [comment]
I have the same behaviour using Volusonic.  Last.fm shows the now playing track, but doesn't record it.

**Comment by Saiyato** [comment]
Apologies for the late reply, but I'm working on a few other plugins. Next phase will include some major refactoring for the authentication flow and I will look into the supported services as well.

If you're using version 1.3.4; you can _just_ add the service name and it "should" work straight away. The list of default services is: `mpd,airplay,volspotconnect,volspotconnect2,spop`. If the service handles track artists and titles differently, you might run into scrobbling errors, but if the "now playing" is displaying correctly, you don't have to worry :wink:

**Comment by Saiyato** [comment]
The new version automatically tries to scrobble from all services, unless they're blacklisted (other way around). Please install version 1.5.2 and up
