### ISSUE TITLE
Don't trigger notifications when submitting scrobbles

### ISSUE THREAD

**Issue by Jucgshu** [Saiyato/volumio-lastfm-plugin#2]
Hi Sayato,

Great extension that works well.

Only thing is that we should prevent notifications to pop up in Volumio UI when scrobbling is done (even successfully). This is a piece of information that belongs in the logs only.

As always, thanks for your work!

-j

**Comment by Saiyato** [comment]
Hi,

I'm not sure I understand, you can turn the messaging off in the plugin. That's why I created the setting.

Please advise

**Comment by Jucgshu** [comment]
My bad, I didn't see that option.

Sry for this mate ;-)
