### ISSUE TITLE
Web Radio scrobbles station name as artist

### ISSUE THREAD

**Issue by theinfguy** [Saiyato/volumio-lastfm-plugin#21]
Hi, I have noticed that when scrobbling a web radio feed, it is ignoring the 'First part is artist name' option and is scrobbling the station name as the artist. Please see screenshots. I thought this option is supposed to split the track into Artist - Title, using the "-" as the split?

![scrobble settings](https://user-images.githubusercontent.com/92925859/148233587-7038a75c-f7f1-4483-b634-a7747e32a4ec.png)

![lastfm scrobbles](https://user-images.githubusercontent.com/92925859/148233614-067cf737-c326-43a6-bb85-2381760ce546.png)

**Comment by lepis0** [comment]
I found this same bug today.

Here is what is playing:
![image](https://user-images.githubusercontent.com/15526120/148988806-4714b24a-b367-40c5-bf32-8492f664f6c0.png)

Here are settings:
![image](https://user-images.githubusercontent.com/15526120/148988489-d2e83487-ed08-4235-bbeb-c0cf294f0fef.png)

last.fm shows :
![image](https://user-images.githubusercontent.com/15526120/148988922-6f5b70f7-6043-485d-8af8-406f669229c8.png)

**Comment by Saiyato** [comment]
Confirmed and found where the condition is lacking

**Comment by Saiyato** [comment]
Found another issue, if the webradio is playing commercials/the news, the title is similar to the artist, but not necessarily the same. This is quite a bummer, because this introduces complexity.

Not a problem for 'now playing' or the web UI, but scrobbling this info is pretty much inserting garbage.
