### ISSUE TITLE
Plugin scrobbles streams even though 'Scrobble streams?' is turned off

### ISSUE THREAD

**Issue by raev33** [Saiyato/volumio-lastfm-plugin#23]
As the title says the plugin scrobbles titles from streams even though 'Scrobble streams?' is turned off.

I presume that this setting should turn off scrobbling from ex. webradio, but this is not the case, as I can see scrobbles from BBC etc.

Is this intended or a bug?

I use LastFM scrobbler version 1.5.6
Volumio version 3.198

**Comment by Saiyato** [comment]
Hi,

Good find! That setting is actually deprecated, it will automatically scrobble anything, unless you blacklist the service. You can add webradio to the blacklisted services. I will actually remove this option in the next release (currently working on something else in the plugin).

Apologies for the inconvenience.

**Comment by raev33** [comment]
Thanks! It works as intended when i write 'webradio' in the blacklist field.

A suggestion: Maybe you could highlight the most common commands that blacklists plugins under the info-button, or write where to find these commands.
Right now it isn't obvious that 'volspotconnect2' will blacklist a Spotify plugin, or that you have to 'webradio' to block webradio.

But maybe it is the blacklist function that you are going to remove altogether in the next release? If so, I think it would be a shame as it's quite a useful feature. Especially for those of us that listen to radiostreams with faulty metadata.

Anyhow thanks for your work and a great plugin!
