### ISSUE TITLE
adding spop to scrobling

### ISSUE THREAD

**Issue by cortegedusage** [Saiyato/volumio-lastfm-plugin#4]
Would it be possible to add spop to scrobling,  and would it be as simple to 
add it to line 66 and 88 of index.js. in the same way mpd and airplay is added?

not at home right now so can't check.

happy new year

dennis

**Comment by cortegedusage** [comment]
when changing the above there does seem to happen something.
the logging looks like there is something going good.
but it also says timer should be there....

not there yet..

grt

Jan 03 14:22:18 woonkamer volumio[1030]: info: --------------------------------------------------------------------// [LastFM] new state has been pushed; status: stop | service: spop | duration: 404 | title: Comfortably Numb | previous title: Comfortably Numb
Jan 03 14:22:18 woonkamer volumio[1030]: info: [LastFM] stopping timer, song has ended.
Jan 03 14:22:18 woonkamer volumio[1030]: info: [LastFM] timer should be there... using the existing instance
Jan 03 14:22:18 woonkamer volumio[1030]: info: --------------------------------------------------------------------// [LastFM] new state has been pushed; status: stop | service: spop | duration: 404 | title: Comfortably Numb | previous title: Comfortably Numb
Jan 03 14:22:18 woonkamer volumio[1030]: info: [LastFM] stopping timer, song has ended.
Jan 03 14:22:18 woonkamer volumio[1030]: info: [LastFM] timer should be there... using the existing instance
Jan 03 14:22:18 woonkamer volumio[1030]: info: --------------------------------------------------------------------// [LastFM] new state has been pushed; status: play | service: spop | duration: 216 | title: Lady Day and John Coltrane | previous title: Comfortably Numb
Jan 03 14:22:18 woonkamer volumio[1529]: 2018-01-03 14:22:18 [SPTF] 14:22:18.346 I [file_streamer_simple.cpp:769] Request for file 018720e2a6e9c1405ad906eb8c3017d0661b3296 complete (code: 0)
Jan 03 14:22:18 woonkamer volumio[1529]: 2018-01-03 14:22:18 [SPTF] 14:22:18.454 I [file_streamer_simple.cpp:769] Request for file 018720e2a6e9c1405ad906eb8c3017d0661b3296 complete (code: 0)
Jan 03 14:22:30 woonkamer volumio[1529]: 2018-01-03 14:22:30 [SPTF] 14:22:30.058 I [file_streamer_simple.cpp:769] Request for file 018720e2a6e9c1405ad906eb8c3017d0661b3296 complete (code: 0)

**Comment by Saiyato** [comment]
I just updated the timer to the latest version, my local version was way ahead of the github version.
After that has been merged into Volumio I will try to see what spop does exactly.

**Comment by cortegedusage** [comment]
I'd like to report that it now works.
So this could be done for any service as long as it passes the info correct?

Cool!
thank you!

**Comment by Saiyato** [comment]
Yes, I'm not sure if I should sift through the services... it does make it a bit safer.... but any service pushing volatile states should work yes.

I'll see if I can limit the services using a setting, so users can choose themselves if they want to use known services only.

**Comment by cortegedusage** [comment]
would be great to have the choice, 
But then do you have to check whether a service is installed?
or would you just list all known services and let the user decide?
