### ISSUE TITLE
Add runtime for the queue/playlist?

### ISSUE THREAD

**Issue by webodan** [Saiyato/volumio-lastfm-plugin#9]
On Volumio's web interface (playback section), you can see the full runtime of the individual track you're playing at the moment, but if you add entire albums or several spare tracks, you can't find the runtime of the entire playlist. I consider that to be a glaring omission. Could it be added?

**Comment by Saiyato** [comment]
You want something added to the Volumio UI? I don't understand.
If you want something added to Volumio (I'm not the author of Volumio) you should raise an issue on the Volumio github page. 

The run time of the entire playlist doesn't really affect LastFM scrobbling imho.

Please advise.

**Comment by webodan** [comment]
Oh, crap i'm an idiot. I'll do that. Sorry. Delete this it was really a mistake to put it in here.

**Comment by Saiyato** [comment]
Hehe nog problem, will close the issue.
